config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post '/events/:id/attendances/new', to: 'attendances#create'
  root 'events#index'
  resources :events
  resources :users

  resources :events, only: [:show] do
    resources :attendances, only: [:new, :create, :index]
  end

  resources :events, only: [:show] do
    resources :images, only: [:create]
  end

  resources :admin, only: [:index]
  delete '/admin', to: 'users#destroy'
  get '/admin/events', to: 'admin#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	after_create :admin_send

	belongs_to :event
	belongs_to :user

	def admin_send
	    AttendanceMailer.admin_email(self.event.administrator).deliver_now
	end
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image
	has_many :attendances, dependent: :destroy
	has_many :users, through: :attendances, dependent: :destroy
  belongs_to :administrator, class_name: "User"

  validates :start_date, presence: true, if: :is_datetime_passed?
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 1000 }
  validates :location, presence: true

  def is_datetime_passed?
    if start_date < Date.today
      return false
    else
      return true
    end
  end

  def end_date
    return start_date + duration
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
	after_create :welcome_send
	has_many :admin_events, foreign_key: 'administrator_id', class_name: "Event", dependent: :destroy
	has_many :attendances, dependent: :destroy
	has_many :events, through: :attendances, dependent: :destroy

	def welcome_send
	    UserMailer.welcome_email(self).deliver_now
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :is_current_user, only: [:index]

  def show
    @events = Event.all
  end
  
  def index
    @users = User.all
  end

  private

  def is_current_user
    unless current_user.admin == true
      flash[:error] = "You do not have the permissions."
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :is_current_user, only: [:index]
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @attendance = Attendance.new
    @event = Event.find(params[:event_id])
  end

  def show
  end

  def index
    @event = Event.find(params[:event_id])
  end

  def create
    @amount = Event.find(params[:id]).price
    @event = Event.find(params[:id])
    # Before the rescue, at the beginning of the method
    @stripe_amount = (@amount * 100).to_i
    begin
      customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
      })
      charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @stripe_amount,
      description: "Achat d'un produit",
      currency: 'eur',
      })
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to attendance_path
    end
    # After the rescue, if the payment succeeded
    @attendance = Attendance.create(stripe_customer_id: params[:id].to_s, user: current_user, event: @event)
    redirect_to root_path
  end

  private

  def is_current_user
    @user = current_user
    unless @user.id == Event.find(params[:event_id]).administrator.id
      flash[:error] = "You don't have the permissions."
      redirect_to root_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new]
  #before_action :is_current_user, only: [:create]

  def show
    @event = Event.find(params[:id])
  end

  def index
    @event = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.administrator = current_user
    if @event.save
      @event.image.attach(io: File.open(Rails.root.join("app", "assets", "images", "Card.png")), filename: 'Card.png' , content_type: "image/png")
      flash[:success] = "Félicitations ! L'événement a été créé !"
      redirect_to root_path
    else
      flash.now[:error] = "L'événement n'a pas été créé ! Veuillez réessayer."
      render new_event_path
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(params[:id])
    else
      flash.now[:error] = "L'événement n'a pas été modifié ! Veuillez réessayer."
      render edit_event_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:success] = "Félicitations ! L'événement a été supprimé !"
      redirect_to root_path
    else
      flash.now[:error] = "L'événement n'a pas été détruit ! Veuillez réessayer."
      render event_path
    end
  end

  private

  def event_params
    event_params = params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :image)
  end

  def is_current_user
    unless current_user.id == Event.find(params[:id]).administrator || current_user.admin == true
      flash[:danger] = "Please log in."
      redirect_to root_path
    end
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.image.attach(params[:image])
    redirect_to(event_path(@event))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show, :edit]
	before_action :is_current_user, only: [:show, :edit]

  def show
    @user = User.find(params[:id])
    @event = Event.where(administrator_id: params[:id])
  end

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(params[:id])
    else
      flash.now[:error] = "L'utilisateur n'a pas été modifié ! Veuillez réessayer."
      render edit_user_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "Félicitations ! Le user a été supprimé !"
      redirect_to admin_path
    else
      flash.now[:error] = "Le user n'a pas été détruit ! Veuillez réessayer."
      render user_path
    end
  end

  private

  def is_current_user
    unless current_user.id.to_i == params[:id].to_i || current_user.admin == true
      flash[:error] = "Please log in."
      redirect_to root_path
    end
  end

  def user_params
    user_params = params.require(:user).permit(:first_name, :last_name, :description, :email)
  end

end

app/helpers/admin_helper.rb
module AdminHelper

	def is_admin
		if current_user.admin == true
			return true
		else
			return false
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def bootstrap_class_for_flash(type)
	  case type
	    when 'notice' then "alert-info"
	    when 'success' then "alert-success"
	    when 'error' then "alert-danger"
	    when 'alert' then "alert-warning"
	  end
	end
	
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                  Utilisateurs <span class="sr-only"></span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/admin/events">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                  Événements
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"><div class="chartjs-size-monitor" style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>


          <h2>Utilisateurs</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Prénom</th>
                  <th>Nom</th>
                  <th>Description</th>
                  <th>Email</th>
                </tr>
              </thead>
              <tbody>
              	<% @users.each do |user| %>
                <tr>
                  <td><%= user.id %></td>
                  <td><%= user.first_name %></td>
                  <td><%= user.last_name %></td>
                  <td><%= user.description %></td>
                  <td><%= user.email %></td>
                  <td><a href="/users/<%= user.id %>" class="btn btn-primary">Voir</a></td>
                  <td><a href="/users/<%= user.id %>/edit" class="btn btn-primary">Éditer</a></td>
                  <td><%= button_to "Supprimer", {:controller => "users", :action => 'destroy', :id => user.id}, :method => :delete, class: "btn btn-danger" %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

app/views/admin/show.html.erb
<div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="/admin">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                  Utilisateurs <span class="sr-only"></span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                  Événements
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"><div class="chartjs-size-monitor" style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>


          <h2>Utilisateurs</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Titre</th>
                  <th>Prix</th>
                  <th>Lieu</th>
                  <th>Durée</th>
                  <th>Date et heure</th>
                </tr>
              </thead>
              <tbody>
              	<% @events.each do |event| %>
                <tr>
                  <td><%= event.id %></td>
                  <td><%= event.title %></td>
                  <td><%= event.price %></td>
                  <td><%= event.location %></td>
                  <td><%= event.duration %> min</td>
                  <td><%= event.start_date.strftime("%d %b %Y à %H:%M") %></td>
                  <td><a href="/events/<%= event.id %>" class="btn btn-primary">Voir</a></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

app/views/attendances/_cards.html.erb
	<% @event.users.each_with_index do |attendant, index| %>
		<div class="card col mb-4 <% if index %2 != 0 %>ms-4<% end %>" style="width: 20rem;">
		  	<div class="card-body wrap row">
		  	<div class="col-2 text-center align-middle">
		  		<img src="https://img.icons8.com/ios-glyphs/30/000000/user-male--v1.png" style="height: 60px;">
		    </div>
		    <div class="col">
			    <h5 class="card-title"><%= attendant.first_name %> <%= attendant.last_name %></h5>
			    <h6 class="fw-normal text-muted"><%= attendant.email %></h6>
			    <p class="card-text"><%= attendant.description %></p>
		    </div>
		  </div>
		</div>
	<% end %>

app/views/attendances/_form.html.erb
<%= form_tag @attendances do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Achat d'un produit"
    data-amount="<% @stripe_amount %>"
    data-locale="auto">
</script>
<% end %>

app/views/attendances/index.html.erb
<div class="container">
	<h2 class="my-4 text-center">Événement</h2>
		<div class="card text-center">
		  <div class="card-header">
		  </div>
		  <% if @event.image.attached? %>
		  <div class="card-img-top" style="height: 18rem; background-image: url(<%= url_for(@event.image) %>); background-size: cover;"></div>
		  <% end %>
		  <div class="card-body">
		    <h5 class="card-title"><%= @event.title %></h5>
		    <p class="card-text small">Description</p>
		    <p class="card-text"><%= @event.description %></p>
		    <p class="card-text"><%= @event.start_date.strftime("Commence le %d %b %Y à %H:%M") %><%= @event.end_date.strftime(", fini le %d %b %Y à %H:%M") %></p>
		    <p class="card-text">Lieu : <%= @event.location %></p>
		    <p class="card-text">Prix : <%= @event.price %> €</p>
		    <a href="/" class="btn btn-primary">Home</a>
		    <a href="/events/<%= @event.id %>/edit" class="btn btn-primary">Éditer</a>
		    <%= button_to "Supprimer", @event, :method => :delete, class: "btn btn-danger mt-3" %>
		  </div>
		  </div>
		  <div class="card-footer text-muted text-center">
		    <%= @event.created_at.strftime("Créé le %d %b %Y à %H:%M") %>
		  </div>
	<% if @event.users.count > 0 %>
  	<h2 class="my-4 text-center">Voici les participants de <%= @event.title %></h2>
        <div class="row d-flex justify-content-center">
        	<%= render "cards" %>
	    </div>
	<% end %>
</div>

app/views/attendances/new.html.erb
<div class="container">
	<h2 class="my-4 text-center">Événement</h2>
		<div class="card text-center">
		  <div class="card-header">
		  </div>
		  <div class="card-body">
		    <h5 class="card-title"><%= @event.title %></h5>
		    <p class="card-text small">Description</p>
		    <p class="card-text"><%= @event.description %></p>
		    <p class="card-text"><%= @event.start_date.strftime("Commence le %d %b %Y à %H:%M") %>, et dure <%= @event.duration %> minutes</p>
		    <p class="card-text">Lieu : <%= @event.location %></p>
		    <p class="card-text">Prix : <%= @event.price %> €</p>
		    <p class="mt-3"><%= render "attendances/form" %></p>
		    <a href="/" class="btn btn-primary">Home</a>
		  </div>
		  </div>
		  <div class="card-footer text-muted text-center">
		    <%= @event.created_at.strftime("Créé le %d %b %Y à %H:%M") %>
		  </div>
</div>

app/views/events/_banner.html.erb
	<div class="p-5 mb-4 jumbo-bg-lg text-light rounded-3">
      <div class="container-fluid py-5">
	    <h1 class="display-5 fw-bold">Mon Super Site d'Events</h1>
        <p class="col-md-8 fs-4">Bonjour à toi nouveau visiteur, bienvenue sur le meilleur site d'event du tieks .. Premiers sur l'event.</p>
        <a class="btn btn-warning btn-lg" href="/events/new" role="button">Poster un event</a>
      </div>
    </div>

app/views/events/_cards.html.erb
	<% Event.all.each_with_index do |event, index| %>
		<div class="card col <% if index > 0 || index == 3 || index == 6 %>ms-4<% end %> p-0" style="width: 20rem;">
		  <div class="card-img-top" style="min-height: 180px; background-image: url(<%= url_for(event.image) %>); background-size: cover;"></div>
		  <div class="card-body wrap">
		    <h5 class="card-title"><%= event.title %></h5>
		    <h6 class="fw-normal text-warning fw-bold">15 Nov 2021 à 15h00</h6>
		    <h6 class="fw-normal text-muted"><%= event.location %></h6>
		    <p class="card-text"><%= event.description %></p>
		    <a href="<%= event_path(event.id)%>"></a>
		    <img src="https://img.icons8.com/ios-glyphs/30/000000/user-male--v1.png" style="height: 25px;">
		    <span class="fw-bold"><%= event.users.count %> Participants</span>
		  </div>
		</div>
	<% end %>

app/views/events/_form.html.erb
		    <%= form_for @event, class: 'my-3 form-style' do |f| %>
		    <h1 class="display-4 font-weight-bold">Créer un événement</h1>

		    <div class="form-floating">
		      <%= f.text_field :title, class: 'form-control', placeholder: 'Titre' %>
		      <%= f.label 'Titre' %>
		      </div>

		      <div class="form-floating">
		      <%= f.text_field :description, class: 'form-control', placeholder: 'Description' %>
		      <%= f.label 'Description' %>
		      </div>

		      <div class="form-floating">
		      <%= f.number_field :price, class: 'form-control', placeholder: 'Prix' %>
		      <%= f.label 'Prix' %>
		      </div>

		      <div class="form-floating">
		      <%= f.text_field :location, class: 'form-control', placeholder: 'Lieu' %>
		      <%= f.label 'Lieu' %>
		      </div>

		      <%= f.file_field :image, class: 'form-control mt-3' %>
		      <br />

		      <%= label_tag 'Durée' %>
		      <%= f.select :duration, options_for_select([["5 minutes", 5], ["10 minutes", 10], ["15 minutes", 15], ["20 minutes", 20], ["25 minutes", 25], ["30 minutes", 30], ["35 minutes", 35], ["40 minutes", 40], ["45 minutes", 45], ["50 minutes", 50], ["55 minutes", 55], ["60 minutes", 60]]), class: 'form-control btn-check' %>
				<br /><br />

			<%= label_tag 'Date' %>
			<%= f.datetime_select :start_date, :order => [:day, :month, :year], class: 'form-control btn-check' %>
			<br />

		      <%= submit_tag "Créer l'événement", class: 'btn btn-dark mt-3' %>
		    <% end %>

app/views/events/_show.html.erb
<div class="container">
	<h2 class="my-4 text-center">Événement</h2>
		<div class="card text-center">
		  <div class="card-header">
		  </div>
		  <div class="card-body">
		    <h5 class="card-title"><%= @event.title %></h5>
		    <p class="card-text small">Description</p>
		    <p class="card-text"><%= @event.description %></p>
		    <p class="card-text small">Email de l'organisateur</p>
		    <p class="card-text"><%= @event.administrator.email %></p>
		    <p class="card-text"><%= @event.start_date.strftime("Commence le %d %b %Y à %H:%M") %><%= @event.end_date.strftime(", fini le %d %b %Y à %H:%M") %></p>
		    <p class="card-text">Lieu : <%= @event.location %></p>
		    <p class="card-text">Prix : <%= @event.price %> €</p>
		  </div>
		  </div>
		  <div class="card-footer text-muted text-center">
		    <%= @event.created_at.strftime("Créé le %d %b %Y à %H:%M") %>
		  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
	<div class="jumbotron p-3 p-md-5 text-black rounded bg-light mt-3">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-weight-bold">Modifier un event</h1>
		    <%= form_for @event, class: 'my-3' do |f| %>

		    	<%= label_tag 'Titre' %>
		      <%= f.text_field :title, class: 'form-control' %>
		      <br />

		      <%= label_tag 'Description' %>
		      <%= f.text_field :description, class: 'form-control' %>
		      <br />

		      <%= label_tag 'Prix' %>
		      <%= f.number_field :price, class: 'form-control' %>
		      <br />

		      <%= label_tag 'Lieu' %>
		      <%= f.text_field :location, class: 'form-control' %>
		      <br />

		      <%= label_tag 'Durée' %>
		      <%= f.select :duration, options_for_select([["5 minutes", 5], ["10 minutes", 10], ["15 minutes", 15], ["20 minutes", 20], ["25 minutes", 25], ["30 minutes", 30], ["35 minutes", 35], ["40 minutes", 40], ["45 minutes", 45], ["50 minutes", 50], ["55 minutes", 55], ["60 minutes", 60]]), class: 'form-control btn-check' %>
				<br /><br />

			<%= label_tag 'Date' %>
			<%= f.datetime_select :start_date, :order => [:day, :month, :year], class: 'form-control btn-check' %>
			<br />

		      <%= submit_tag "Modifier l'événement", class: 'btn btn-dark mt-3' %>
		    <% end %>
		    <%= form_tag event_images_path(@event), multipart: true do %>
			  <%= file_field_tag :image, class: 'form-control mt-3' %>
			  <%= submit_tag "Mettre à jour l'image", class: 'btn btn-dark mt-3' %>
			<% end %>
        </div>
      </div>
	</div>

app/views/events/index.html.erb
<%= render "banner" %>
		<h2 class="my-4 text-center">Voici la liste de tous les événements</h2>
		<div class="container">
        <div class="row d-flex justify-content-center">
        	<%= render "cards" %>
        </div>

      </div>

app/views/events/new.html.erb
<div class="container">
	<div class="jumbotron p-3 p-md-5 text-black rounded bg-light mt-3">
        <div class="col-md-6 px-0">
        	<%= render "form" %>
        </div>
      </div>
	</div>

app/views/events/show.html.erb
<div class="container">
	<h2 class="my-4 text-center">Événement</h2>
		<div class="card text-center">
		  <div class="card-header"></div>
		  <% if @event.image.attached? %>
		  <div class="card-img-top" style="height: 18rem; background-image: url(<%= url_for(@event.image) %>); background-size: cover;"></div>
		  <% end %>
		  <div class="card-body">
		    <h5 class="card-title"><%= @event.title %></h5>
		    <p class="card-text small">Description</p>
		    <p class="card-text"><%= @event.description %></p>
		    <p class="card-text small">Email de l'organisateur</p>
		    <p class="card-text"><%= @event.administrator.email %></p>
		    <p class="card-text"><%= @event.start_date.strftime("Commence le %d %b %Y à %H:%M") %>, et dure <%= @event.duration %> minutes</p>
		    <p class="card-text">Lieu : <%= @event.location %></p>
		    <p class="card-text">Prix : <%= @event.price %> €</p>
		    <a href="/" class="btn btn-primary">Home</a>
		    <% if current_user.nil? == false && current_user.id == @event.administrator.id %>
		    <a href="/events/<%= @event.id %>/attendances" class="btn btn-primary">Espace événement</a>
		    <% elsif current_user.nil? == false && current_user.id != @event.administrator.id %>
		    <a class="btn btn-warning" href="/events/<%= @event.id %>/attendances/new" role="button">Participer</a>
		    <% end %>
		  </div>
		  </div>
		  <div class="card-footer text-muted text-center">
		    <%= @event.created_at.strftime("Créé le %d %b %Y à %H:%M") %>
		  </div>
</div>

app/views/layouts/_flash.html.erb
  <% flash.each do |type, msg| %>
    <div class="alert <%= bootstrap_class_for_flash(type) %> mb-0 text-center">
      <%= msg %>
    </div>
  <% end %>

app/views/layouts/_footer.html.erb
	  <footer class="py-3">
	    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
	      <li class="nav-item"><a href="/" class="nav-link px-2 text-warning">Home</a></li>
	      <li class="nav-item"><a href="/" class="nav-link px-2 text-warning">Events</a></li>
	    </ul>
	    <p class="text-center text-warning">© 2021 Eventbrite, Inc</p>
	  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteLike</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
    <%= render "layouts/navbar" %>
  <body>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
    <%= render "layouts/footer" %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>